Frontend:
  impl: SimpleO3
  clock_ratio: 1
  num_expected_insts: 500000
  traces: 
    - example_inst.trace

  Translation:
    impl: NoTranslation
    max_addr: 2147483648
              

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 1
  DRAM:
    impl: HBM3
    org:
      preset: HBM3_8Gb
      channel: 16
    timing:
      preset: HBM3_2Gbps

  Controller:
    impl: HBM3
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBankHBM3
    plugins:
    - ControllerPlugin:
        impl: HBM3TraceRecorder
        path: ./log/base/cmd.log

  AddrMapper:
#    impl: HBM3-Base
    impl: HBM3-Custom
